pipeline {
  environment {
    PATH = "$PATH:/usr/bin"
  }
    agent any
    stages {
        // stage('Setup') {
        //     steps {
        //         script {
        //             properties([parameters([choice(choices: ['QA', 'PROD']),
        //             choice(choices: ['Goldmine', 'Palladium'])])])
        //         }
        //     }
        // }
        // stage('Build') {
        //     steps {
        //         // Build the Docker image
        //         sh 'docker-compose build'
        //     }
        // }
        stage('Test') {
            steps {
              echo "PATH is: $PATH"
                // Run the Playwright tests
                sh '/usr/bin/ ENV=prod docker-compose up --build'
            }
        }
        stage('Tear Down') {
            steps {
                // Down docker images
                sh '/usr/bin/ docker-compose down --remove-orphans'
            }
        }
    }
}