pipeline {
    agent any
    stages {
        // stage('Setup') {
        //     steps {
        //         script {
        //             properties([parameters([choice(choices: ['QA', 'PROD']),
        //             choice(choices: ['Goldmine', 'Palladium'])])])
        //         }
        //     }
        // }
        // stage('Build') {
        //     steps {
        //         // Build the Docker image
        //         sh 'docker-compose build'
        //     }
        // }
        stage('Test') {
            steps {
                // Run the Playwright tests
                sh 'docker compose up'
                // sh 'docker --version'
            }
        }
        stage('Tear Down') {
            steps {
                // Down docker images
                sh 'docker compose down'
            }
        }
    }
}