name: Playwright Test

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run Playwright tests
        run: |
          docker-compose up --build

      - name: Tear down Docker Compose
        run: |
          docker-compose down
